### ISSUE TITLE
Height doesn't seem to be set correctly

### ISSUE THREAD

**Issue by yankeyhotel** [CodyHouse/cd-overscroll-gallery-changelog#1]
The height doesn't seem to be large enough to contain the gallery causing images to go off the right side of the browser. If I increase the height of the `. masonry__list` (through the chrome dev console) then it has room to accommodate all of the images. I can't see a setting to give it more height by default.

I literally copied and pasted the demo into my site so I am not sure what is going wrong. Using Chrome and macOS Big Sur 11.6

https://user-images.githubusercontent.com/1146801/138508734-2eb6f9d0-1846-419a-83fb-df6fea636fc6.mp4

**Comment by claudia-romano** [comment]
Hi there, the height of the gallery is set automatically in JS based on the images layout, that's why you cannot manually modify it. 

From your video, it looks like the Masonry component is not working properly. May I ask if you included the JS/CSS code of the dependencies as well? You can find the complete list here:
https://codyhouse.co/ds/components/info/overscroll-gallery

Thanks!

**Comment by claudia-romano** [comment]
Hi there, I'm closing this issue as no additional info was provided. Feel free to reopen it if you are still experiencing the problem. Thanks!
